services:
  nginx-exporter:
    image: nginx/nginx-prometheus-exporter:latest
    container_name: nginx-exporter
    networks:
      - rb
    ports:
      - "9113:9113"
    command:
      - "-nginx.scrape-uri=http://web/nginx_status"

  rabbitmq-exporter:
    image: kbudde/rabbitmq-exporter
    container_name: rabbitmq-exporter
    networks:
      - rb
    ports:
      - "9419:9419"

  mongodb-exporter:
    image: bitnami/mongodb-exporter:latest
    container_name: mongodb-exporter
    networks:
      - rb
    ports:
      - "9216:9216"
    command:
      - "--mongodb.uri=mongodb://mongo:27017"

  mysql-exporter:
    image: prom/mysqld-exporter
    container_name: mysql-exporter
    networks:
      - rb
    ports:
      - "9104:9104"
    environment:
      - DATA_SOURCE_NAME=root:RoboShop@1@(mysql:3306)/

  redis-exporter:
    image: oliver006/redis_exporter
    container_name: redis-exporter
    networks:
      - rb
    ports:
      - "9121:9121"

networks:
  rb:
    external: true
