networks:
  rb:
    driver: bridge
    
services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    networks:
      - rb
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    restart: always

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    networks:
      - rb
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin123
    restart: always

volumes:
  grafana-data: